language: rust

cache: cargo

rust:
  - nightly
  - beta
  - stable

# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libssl-dev
      - libssl1.0.0
      - cmake
    sources:
      - kalakris-cmake

before_install:
  - export ROOT_PATH=`pwd`

before_script:
  - |
      cargo install --force cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH

script:
  - cd $ROOT_PATH/lib     && cargo test
  - cd $ROOT_PATH/command && cargo test
  - cd $ROOT_PATH/bin     && cargo build
  - cd $ROOT_PATH/ctl     && cargo build

after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo coveralls --all --verbose;
    fi

dist: trusty

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a8be0f69e0165e590dcb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
